openapi: 3.0.3
info:
  contact:
    email: mikita.zdanovich@godeltech.com
  description: SDET MASTERY SANDBOX
  title: Godel Petstore
  version: 1.0.3
servers:
  - url: http://localhost:3000
  - url: https://petstore.godel
paths:
  /user:
    post:
      description: This can only be done by the logged in user.
      operationId: createUser
      security: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        description: Created user object
        required: true

      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
          description: successful operation
        "405":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Failed to create user
      summary: Create user
      tags:
        - user
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/UserController
    delete:
      description: This can only be done by the logged in user.
      operationId: deleteUser
      parameters:
        - description: The name that needs to be deleted
          explode: false
          in: header
          name: username
          required: true
          schema:
            type: string
          style: simple
      responses:
        "400":
          content: { }
          description: Invalid username supplied
        "404":
          content: { }
          description: User not found
      summary: Delete user
      tags:
        - user
      x-eov-operation-handler: controllers/UserController
    get:
      operationId: getUserByName
      parameters:
        - description: 'The name that needs to be fetched. Use user1 for testing. '
          explode: false
          in: header
          name: username
          required: true
          schema:
            type: string
          style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
          description: successful operation
        "400":
          content: { }
          description: Invalid username supplied
        "404":
          content: { }
          description: User not found
      summary: Get user by user name
      tags:
        - user
      x-eov-operation-handler: controllers/UserController
    put:
      description: This can only be done by the logged in user.
      operationId: updateUser
      parameters:
        - description: name that need to be updated
          explode: false
          in: header
          name: username
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        description: Updated user object
        required: true
      responses:
        "400":
          content: { }
          description: Invalid user supplied
        "404":
          content: { }
          description: User not found
      summary: Updated user
      tags:
        - user
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/UserController
  /login:
    post:
      operationId: loginUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
          application/xml:
            schema:
              $ref: '#/components/schemas/Login'
        description: Pet object that needs to be added to the store
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
            application/xml:
              schema:
                $ref: '#/components/schemas/Token'
          description: successful operation
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Invalid username/password supplied
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth header required
      summary: Logs user into the system
      security: [ ]
      tags:
        - login flow
      x-eov-operation-handler: controllers/AuthController
  /logout:
    get:
      operationId: logoutUser
      responses:
        default:
          content: { }
          description: successful operation
      summary: Logs out current logged in user session
      tags:
        - login flow
      x-eov-operation-handler: controllers/UserController
  /category:
    post:
      operationId: categoryCreate
      requestBody:
        description: Create category for user
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Category'
      responses:
        "201":
           content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Category'
           description: Created category information
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/StoreController
      tags:
        - category
  /category/{categoryId}:
    get:
      operationId: categoryGet
      parameters:
        - in: path
          name: categoryId
          schema:
            type: integer
          required: true
      responses:
        "200":
           description: Return category info.
           content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Category'
        "404":
          description: Category not found
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/StoreController
      tags:
        - category
  /pet/{petId}:
    get:
      operationId: petGet
      parameters:
        - in: path
          name: petId
          schema:
            type: integer
          required: true
      responses:
        "200":
           description: Return category info.
           content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Pet'
        "404":
          description: Pet not found
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/StoreController
      tags:
        - pet
    delete:
      operationId: petDetele
      parameters:
        - in: path
          name: petId
          schema:
            type: integer
          required: true
      responses:
        "204":
          content: { }
          description: Pet destroyed
      summary: Deletes a pet
      x-codegen-request-body-name: body
      tags:
          - pet
    put:
      operationId: updatePet
      parameters:
        - in: path
          name: petId
          schema:
            type: integer
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetInfo'
        description: Pet object that needs to be added to the store
        required: true
      responses:
        "200":
           description: Return category info.
           content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Pet'
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Invalid ID supplied
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
          description: Pet not found
        "405":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
          description: Validation exception
      summary: Update an existing pet
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/StoreController
      tags:
        - pet
  /pet:
    get:
      description: Retrieve list Pets
      operationId: getPets
      parameters:
        - description: Status values that need to be considered for filter
          in: query
          name: status
          required: false
          schema:
            items:
              default: available
              enum:
                - available
                - pending
                - sold
              type: string
            type: array
          style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Pet'
                type: array
          description: Operation Succeed
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 'Operation failed'
      summary: Get All Pets
      tags:
        - pet
      x-eov-operation-handler: controllers/PetController
      x-eov-operation-id: getPets
    post:
      operationId: addPet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetInfo'
          application/xml:
            schema:
              $ref: '#/components/schemas/Pet'
        description: Pet object that needs to be added to the store
        required: true
      responses:
        "201":
           content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
           description: Created pet information
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
          description: Invalid input
      summary: Add a new pet to the store
      tags:
        - pet
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/PetController
  /pet/uploadImage:
    post:
      operationId: uploadFile
      parameters:
        - description: ID of pet to update
          explode: false
          in: header
          name: id
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  description: file to upload
                  format: binary
                filename:
                  type: string
                  description: name of image
            encoding:
              file:
                contentType: image/png, image/jpeg
      responses:
        "200":
          content:
            { }
          description: successful operation
        "405":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 'Operation failed'
      security:
        - bearerAuth: [ ]
      summary: uploads an image
      tags:
        - pet

      x-eov-operation-handler: controllers/PetController
      x-eov-operation-id: uploadPetImage
  /store/order:
    post:
      operationId: placeOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        description: order placed for purchasing the pet
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
          description: successful operation
        "400":
          content: { }
          description: Invalid Order
      summary: Place an order for a pet
      tags:
        - store
  /store/order/{orderId}:
    delete:
      description: For valid response try integer IDs with positive integer value.
        Negative or non-integer values will generate API errors
      operationId: deleteOrder
      parameters:
        - description: ID of the order that needs to be deleted
          explode: false
          in: path
          name: orderId
          required: true
          schema:
            format: int64
            minimum: 1
            type: integer
          style: simple
      responses:
        "400":
          content: { }
          description: Invalid ID supplied
        "404":
          content: { }
          description: Order not found
      summary: Delete purchase order by ID
      tags:
        - store
      x-eov-operation-handler: controllers/StoreController
    get:
      description: For valid response try integer IDs with value >= 1 and <= 10. Other
        values will generated exceptions
      operationId: getOrderById
      parameters:
        - description: ID of pet that needs to be fetched
          explode: false
          in: path
          name: orderId
          required: true
          schema:
            format: int64
            maximum: 10
            minimum: 1
            type: integer
          style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
          description: successful operation
        "400":
          content: { }
          description: Invalid ID supplied
        "404":
          content: { }
          description: Order not found
      summary: Find purchase order by ID
      tags:
        - store
      x-eov-operation-handler: controllers/StoreController
  /store/inventory:
    get:
      description: Returns a map of status codes to quantities
      operationId: getInventory
      responses:
        "200":
          content:
            application/json:
              schema:
                additionalProperties:
                  format: int32
                  type: integer
                type: object
          description: successful operation
      summary: Returns pet inventories by status
      tags:
        - store
      x-eov-operation-handler: controllers/StoreController
components:
  schemas:
    Login:
      example:
        username: Username
        password: Password
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
    Token:
      example:
        accssToken: jtwToken
        refreshToken: jwtRefreshToken
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
    Error:
      example:
        code: 400
        message: 'Bad request'
        errors: 'Bad request'
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        errors:
          description: Errors object
    PetInfo:
      example:
        name: doggie
        categoryId: 6
        status: available
      properties:
        category:
          type: integer
        name:
          example: doggie
          type: string
        status:
          description: pet status in the store
          enum:
            - available
            - pending
            - sold
          type: string
      required:
        - name
      type: object
    Pet:
      example:
        id: 130
        name: doggie
        categoryId: 6
        status: available
      properties:
        id:
          type: integer
        category:
          type: integer
        name:
          example: doggie
          type: string
        status:
          description: pet status in the store
          enum:
            - available
            - pending
            - sold
          type: string
      required:
        - name
      type: object
    Tag:
      example:
        name: name
        id: 1
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
      type: object
      xml:
        name: Tag
    Order:
      example:
        petId: 6
        quantity: 1
        id: 0
        shipDate: 2000-01-23T04:56:07.000+00:00
        complete: true
        status: placed
      properties:
        id:
          format: int64
          type: integer
        petId:
          format: int64
          type: integer
        quantity:
          format: int32
          type: integer
        shipDate:
          format: date-time
          type: string
        status:
          description: Order Status
          enum:
            - placed
            - approved
            - delivered
          type: string
        complete:
          type: boolean
      type: object
      xml:
        name: Order
    User:
      example:
        firstname: firstname
        lastname: lastname
        password: password
        phone: phone
        email: email
        username: username
      properties:
        username:
          type: string
          nullable: false
          minLength: 1
        firstname:
          type: string
          nullable: false
          minLength: 1
        lastname:
          type: string
          nullable: false
          minLength: 1
        email:
          type: string
        password:
          type: string
          nullable: false
          minLength: 1
        phone:
          type: string
      required: [ username, firstname, lastname, password ]
      type: object
      xml:
        name: User
    Category:
      example:
        name: "CategoryName"
        description: "Dscription"
      properties:
        name:
          type: string
        description:
          type: string
      type: object
      xml:
        name: Category
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: [ ]